name: Build & Notify Deploy

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
      artifact-name: ${{ steps.upload.outputs.artifact-url }}

    steps:
      - uses: actions/checkout@v6

      # Build your site (example: Astro or MkDocs)
      - name: Build static site
        run: |
          npm ci
          npm run build

      # Create a tarball of the build output
      - name: Create tarball
        run: |
          mkdir -p output
          tar -C dist -czf output/site.tar.gz .

      # Install the latest Minisign dynamically
      - name: Install Minisign
        run: |
          ARCH=$(uname -m)
          LATEST=$(curl -s https://api.github.com/repos/jedisct1/minisign/releases/latest \
            | grep "browser_download_url" \
            | grep "linux" \
            | grep "$ARCH" \
            | grep -v "\.minisig" \
            | cut -d '"' -f 4)
          echo "Downloading $LATEST..."
          curl -sL "$LATEST" -o minisign.tar.gz
          tar -xzf minisign.tar.gz
          sudo mv minisign-linux/$ARCH/minisign /usr/local/bin/
          minisign -V

      # Sign the tarball
      - name: Sign artifact
        env:
          MINISIGN_SECRET_KEY: ${{ secrets.MINISIGN_SECRET_KEY }}
        run: |
          minisign -S -m output/site.tar.gz

      # Upload artifacts (tarball + signature)
      - name: Upload artifact
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: site-deploy
          path: |
            output/site.tar.gz
            output/site.tar.gz.minisig
          overwrite: true

      # Notify webhook
      - name: Send deploy webhook
        run: |
          curl -X POST https://deploy.winlogon.org/deploy \
            -H "Content-Type: application/json" \
            --data-raw "{
              \"area\": \"repos\",
              \"project\": \"whatever\",
              \"owner\": \"<GITHUB_OWNER>\",
              \"repo\": \"<GITHUB_REPO>\",
              \"artifact_id\": \"${{ steps.upload.outputs.artifact-id }}\",
              \"github_token\": \"${{ secrets.GITHUB_TOKEN }}\",
              \"signature\": \"$(cat output/site.tar.gz.minisig | base64)\"
            }"
